workflows:

  maui-ios:
    name: Dotnet MAUI iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.yourcompany.MauiApp1
    vars:
      DOTNET_PATH: $CM_BUILD_DIR/dotnet
      DOTNET: $CM_BUILD_DIR/dotnet/dotnet
    scripts:
      - name: Install dotnet sdk
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH
      - name: Install MAUI workloads
        script: |
          $DOTNET nuget locals all --clear
          $DOTNET workload install ios maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
      - name: Build and publish iOS app
        script: |
          cd MauiApp1
          $DOTNET publish -f net6.0-ios -c Release -p:BuildIpa=true -p:ApplicationDisplayVersion="1.0.0" -p:RuntimeIdentifier=ios-arm64 -o ../artifacts
    artifacts:
      - ./artifacts/*.ipa

  maui-android:
    name: Dotnet MAUI Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - codemagic-key
    vars:
      DOTNET_PATH: $CM_BUILD_DIR/dotnet
      DOTNET: $CM_BUILD_DIR/dotnet/dotnet
      PACKAGE_NAME: "com.yourcompany.MauiApp1"
    scripts:
      - name: Install dotnet sdk
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH
      - name: Install MAUI workloads
        script: |
          $DOTNET nuget locals all --clear
          $DOTNET workload install android maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
      - name: Build and publish Android app
        script: |
          cd MauiApp1
          $DOTNET publish -f net6.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=$CM_KEYSTORE_PATH -p:AndroidSigningKeyAlias=$CM_KEY_ALIAS -p:AndroidSigningKeyPass=$CM_KEY_PASSWORD -p:AndroidSigningStorePass=$CM_KEYSTORE_PASSWORD -p:ApplicationDisplayVersion="1.0.0" -o ../artifacts
    artifacts:
      - ./artifacts/*.apk

